server:
  port: 3011
spring:
  data:
    cassandra:
      keyspace-name: mykeyspace
      contact-points: 35.237.68.44
      port: 9042 #9142
      schema-action: none
      #      username: cassandra
      #      password:
      cluster-name: MyCluster
