server:
  port: 3000

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name: DatabaseTopic

##Crear topico
# bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic DatabaseTopic

##Ver mensajes
# bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic DatabaseTopic --from-beginning
